- name: install nginx and run
  hosts: frontend
  tasks:
   - name: Install nginx
     ansible.bulitin.package:
      name: nginx
      state: present

   - name: start nginx
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
