- name: playing variables
  hosts: local
  connection: local
  vars:
    COURSE: ansible
    DURATION: 5HRS
    TRAINER: Hari
  tasks:
  - name: print course information
    ansible.builtin.ping:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"
